### ISSUE TITLE
Example in the docs has couple of bugs..

### ISSUE THREAD

**Issue by rajaraodv** [sebinsua/neo4j-promised#2]
bug #1. Doesn't have:
 var Q = require('bluebird');

bug #2:  "id" should be a 1st parameter and json data should be 2nd parameter as per node.js, but you are passing json directly causing the  "exampleRelationship.save()" line to throw error.

var example1 = new Node({
  name: '1',
  id: "some-id-goes-here-1"
});

var example2 = new Node({
  name: '2',
  id: "some-id-goes-here-2"
});
var example3 = new Node({
  name: '3',
  id: "some-id-goes-here-3"
});

**Comment by sebinsua** [comment]
Thanks I'll fix a couple of these things tomorrow night - example was obviously written without any actual usage. :P

**Comment by sebinsua** [comment]
Should be better now.
